### ISSUE TITLE
Mod Fix

### ISSUE THREAD

**Issue by SilentGD** [Joxlyn/GDPS-Updates#2]
Hi, i have a problem with the mod, when i request mod it dosent works, actually theres no option in the PHP, i dont found it.

**Comment by RobToxx** [comment]
Yeah, Silent... I have the seem problem...Si, Silent tengo el mismo problema...

**Comment by Joxlyn** [comment]
Hello! For the mod to work, you have to go to your database and look for the column "Accounts" Select an account (which you want to get Moderator) and look for the row "isAdmin" Put there "1", then look for the column "Roles" and create a role (whichever you want) and assign it to the id of the account.

**Comment by Joxlyn** [comment]
You create them manually, just go to the roles table and go to the top and click "insert". you should see a bunch of stuff to fill out. Leave role ID blank and for the rest write 1 if you want to grant a permission or 0 to deny it. For role color, insert an RGB code (https://www.w3schools.com/colors/colors_rgb.asp). Not really sure what "priority" is. As for assigning them, just go to the roleassign table and click "insert" again. You can leave assignID blank and copy/past the role ID and your account ID into the correct places. 
(By: Cvolton)

**Comment by Joxlyn** [comment]
with the most recent version of the gdps source, modBadgeLevel and actionRequestMod accept values 0-2 (0=not a mod, 1=normal mod, 2=elder mod) and modBadgeLevel must be at least 1 for colored comments to work.

Also I recommend creating a normal user role that has isDefault set to 1 (leave it at 0 for all other roles, otherwise the GDPS might get confused and could make all people mods)

Also priority exists because you can assign multiple roles to 1 person, the GDPS always goes from the top to the bottom when checking permissions - setting a permission to 0 means "check if a lower priority role has the permission and if the user requesting it has that lower priority role"

I hope I didn't make this explaination too confusing. I plan to make a role manager in the dashboard later on, but I'm currently focusing on updating the GDPS to 2.11 and getting the system to actually work, since commands for example still depend on the old isAdmin variable instead of the permissions system
(By: Cvolton)

**Comment by RobToxx** [comment]
Oh...Thanks...

**Comment by Joxlyn** [comment]
#3

**Comment by RobToxx** [comment]
i have a new problem with the mod...when i comment (only with the mod) all the comments dissapear...and i dont have the option of modBadgeLevel

**Comment by Joxlyn** [comment]
To find the modBadgeLevel option, you must update your database to the most recent one (04/12/2017). To avoid the error where the comments do not work, you must have the php files updated to the latest version (04/12/2017).
